### ISSUE TITLE
일부 디자인 로직 수정 및 파일 다운로드 방지

### ISSUE THREAD

**Issue by xogk1128** [Scapture-official/Scapture-Client#167]
### ⚠️Issue

- 일부 디자인 로직 수정 및 파일 다운로드 방지

### ✏️Task

- [x] 댓글 좋아요 Heart 이미지 변경
- [ ] S3를 사용하는 경우 url 숨기기
- [ ] 개발자 도구에서의 Url로 파일 접근 막기
- [ ] video의 경우 control 바에서 다운로드 버튼 없애기
- [ ] 마우스 오른쪽 클릭으로 다운로드 금지하기

### 🗓Next Task

- [ ] x
