### ISSUE TITLE
isParking 변경

### ISSUE THREAD

**Issue by xogk1128** [Scapture-official/Scapture-Client#192]
### ⚠️Issue

- isParking 에서 IsFree로 변수명 변경

### ✏️Task

- [x] isParking 에서 IsFree로 변수명 변경
- [x] 메인 페이지
- [x] 경기장 조회
- [x] 경기장 검색
- [x] 경기장 세부 조회
- [x] 영상 세부 조회
- [x] 관리 경기장 조회
- [x] 경기장 생성
- [x] 경기장 편집

### 🗓Next Task

- [x] x
