### ISSUE TITLE
전체적인 디자인 안정화

### ISSUE THREAD

**Issue by xogk1128** [Scapture-official/Scapture-Client#239]
### ⚠️Issue

- 전체적인 디자인 안정화

### ✏️Task

- [x] 전체적인 디자인 안정화
- [x] 영상 세부 페이지 디자인 변경에 맞춰 적용
- [x] 영상 공유 URL 구조 변경
- [x] Apple 관련 브라우저 제외 영상 재생 기능 추가
- [x] 클립보드 복사하기 기능 추가
- [x] 영상 공유 링크로 접속시 Day 선택 안되던 문제 해결하기

### 🗓Next Task

- [x] x
