### ISSUE TITLE
User 결제 및 권한 전체적인 Flow 점검

### ISSUE THREAD

**Issue by xogk1128** [Scapture-official/Scapture-Client#302]
### ⚠️Issue

- User 결제 및 권한 전체적인 Flow 점검

### ✏️Task

- [x] 브릿지 페이지 일시 중단
- [x] LBFS 와 같은 구단은 다운로드 기본 방지 => 구장 마다 다운로드 권한으로 구별
- [x] 하이라이트 요청 결제 추가 및 결제자 버내너 할인
- [x] 하이라이트 요청 테이블 세분화

### 🗓Next Task

- [x] x
