### ISSUE TITLE
회원 탈퇴 페이지 추가

### ISSUE THREAD

**Issue by Beomtae** [Scapture-official/Scapture-Client#310]
### ⚠️Issue

- 회원 탈퇴 페이지 UI 추가

### ✏️Task

- [x] 회원 탈퇴 페이지 UI 추가
- [x] 회원 탈퇴 시 API 연동
- [x] 완료 시 모달 추가

### 🗓Next Task

- X
